[package]
name = "serialization-evaluation"
version = "0.1.0"
authors = ["Adam Cigánek <adam.ciganek@gmail.com>"]

[dependencies]
bincode = "~0.4.0"
cbor = "~0.3.16"
rand = "~0.3.13"
rustc-serialize = "~0.3.16"
serde = "~0.6.7"
serde_macros = "~0.6.5"
serde_json = "*"

[features]
use_rustc_serialize = []
use_serde = []
use_cbor = []
use_bincode = []
explicit_traits = []